add nexus maven
bringg/graphhopper pull request #26
Opened 2020-10-26 10:11 UTC by Shareed2k

2020-10-26 10:48 UTC, shamil requested changes

2020-10-26 10:48 UTC, shamil commented on Jenkinsfile
> +                configFileProvider([configFile(fileId: 'e634cf5d-12c6-41fa-82f9-8bbe8c594220', variable: 'MAVEN_GLOBAL_SETTINGS')]) {
@Shareed2k are we sure we want to do it this way? Is there any posibility to manage the config in this repo directly?
Also `fileId` should have friendlt name not the GUID

2020-10-26 10:48 UTC, shamil commented on api/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd
altering those files is not safe, since as I told you the source is coming from `graphhopper` upstream. Is it possible to do this without altering `pom` files?

2020-10-26 10:51 UTC, shamil commented on pom.xml
> +            <url>https://maven.nexus.integration.gcloud.bringg.com/repository/private_maven2_repo/</url>
can we have different name then `private_maven2_repo` ?

2020-10-26 11:20 UTC, Shareed2k commented on pom.xml
> +            <url>https://maven.nexus.integration.gcloud.bringg.com/repository/private_maven2_repo/</url>
Suggest for the name

2020-10-26 14:42 UTC, Shareed2k commented on Jenkinsfile
> +                configFileProvider([configFile(fileId: 'e634cf5d-12c6-41fa-82f9-8bbe8c594220', variable: 'MAVEN_GLOBAL_SETTINGS')]) {
i can encapsulate it to function like `deployService`

2020-10-26 15:02 UTC, shamil commented on Jenkinsfile
> +                configFileProvider([configFile(fileId: 'e634cf5d-12c6-41fa-82f9-8bbe8c594220', variable: 'MAVEN_GLOBAL_SETTINGS')]) {
no that's fine for now, just make sure you do it on `master` (or what @irisshainsky  prefers) branch, but not all branches

2020-10-26 15:04 UTC, shamil commented on Jenkinsfile
> +        stage('Deploy') {
```suggestion
        stage('Push to Maven') {
```

2020-10-26 15:47 UTC, Shareed2k commented on Jenkinsfile
> +                configFileProvider([configFile(fileId: 'e634cf5d-12c6-41fa-82f9-8bbe8c594220', variable: 'MAVEN_GLOBAL_SETTINGS')]) {
She prefer to do it on all ;)

2020-10-26 15:56 UTC, shamil commented on Jenkinsfile
> +                configFileProvider([configFile(fileId: 'e634cf5d-12c6-41fa-82f9-8bbe8c594220', variable: 'MAVEN_GLOBAL_SETTINGS')]) {
what for?

2020-10-27 12:56 UTC, irisshainsky approved these changes

2020-10-27 13:07 UTC, shamil approved these changes

2020-10-27 13:13 UTC, merged